name: Java CI with SonarCloud and Nexus

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Step 4: Build the project with Maven
      - name: Build with Maven
        run: mvn clean install

      # Step 5: Run SonarCloud analysis
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=rakhidhomane_JavaMavenSonarGithub_CalculatorDemo

      # Step 6: Check SonarCloud Quality Gate
      - name: Check SonarCloud Quality Gate
        id: quality-gate
        run: |
          echo "Checking SonarCloud Quality Gate status..."
          sleep 30 # Wait for the analysis to complete
          response=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=rakhidhomane_JavaMavenSonarGithub_CalculatorDemo")
          status=$(echo $response | jq -r '.projectStatus.status')
          if [ "$status" = "OK" ]; then
            echo "Quality Gate status: SUCCESS"
            echo "QUALITY_GATE_STATUS=SUCCESS" >> $GITHUB_ENV
          else
            echo "Quality Gate status: FAILED"
            echo "QUALITY_GATE_STATUS=FAILED" >> $GITHUB_ENV
            exit 1
          fi
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # Step 7: Deploy Maven artifacts to GitHub Packages
      - name: Deploy Maven Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.TOKENGITHUB}}
        run: mvn deploy -DskipTests=true

     
     
