name: Default Variables Example


on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  print-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Print Variables
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Workflow: ${{ github.workflow }}"
          
      - name: Set Custom Variables
        env:
          MY_VAR: "Hello, World!"
        run: |
           echo "Custom Variable: $MY_VAR"
